### ISSUE TITLE
3.75 m parts

### ISSUE THREAD

**Issue by danfarnsy** [KSP-RO/TacLifeSupport#10]
Let's make this a thing.

**Comment by JPLRepo** [comment]
3.75M parts made including containers and resource converters (did not do hex cans).

**Comment by keyspace** [comment]
@JPLRepo uh, where's this?..

**Comment by JPLRepo** [comment]
@keyspace - uh, who are you?
and they are coming. pushed to dev already. But I'd like to understand who you are?

**Comment by keyspace** [comment]
Just a long-time `TAC-LS` user.

**Comment by JPLRepo** [comment]
Implremented in V0.12.5
