### ISSUE TITLE
Change MM_AddResourcesMFT.cfg

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/TacLifeSupport#100]
Please change
GameData\ThunderAerospace\TacLifeSupportMFT\MM_AddResourcesMFT.cfg
from
LifeSupportAll
to
ServiceModule

because this patch is for crewed pods or crewable parts which also could use EC, Hydrazine etc. pp.

It's not a TAC-LS resource container.

**Comment by JPLRepo** [comment]
This would remove the ability to add life support to the ModuleCommand parts.
TAC LS has it's own tank definitions.
If you wish to mix other resources with life support resources then you can define your own tank type for your install.
