### ISSUE TITLE
None of the parts are showing up.

### ISSUE THREAD

**Issue by Puppythapup** [KSP-RO/TacLifeSupport#102]
There is parts and supplies in the commandpod

**Comment by JPLRepo** [comment]
MY bad... Yeah. Use the Community Category Kit and it will show... using the stock ones it does not.
Due to a change in 1.3.1 that I forgot about. Will fix when I get some time.

**Comment by JPLRepo** [comment]
This will be fixed in the next version for KSP 1.4.1
