### ISSUE TITLE
[1.4.2] hibernated kerbals stays forever tourist after recovery

### ISSUE THREAD

**Issue by tonimark** [KSP-RO/TacLifeSupport#110]
when I recover a hibernated kerbal he stays forever as tourist role at astronaut complex and even after i assign it to a flight causing making kerbal useless

**Comment by JPLRepo** [comment]
I took a look at the code, and it should handle this already.
So I need more information. eg: Where did you recover the vessel from? The KSC? From in flight? From the Tracking Station?
Can you supply a save game with this issue and logs?

**Comment by JPLRepo** [comment]
No information supplied. closing.
