### ISSUE TITLE
[enchantment] kerbals SHOULDN'T spend oxygen resource on breathable atmosphere 

### ISSUE THREAD

**Issue by tonimark** [KSP-RO/TacLifeSupport#111]
plz make kerbals to not spend oxygen resource when they are on a planet with a breathable atmosphere ex:kerbin this is a very real thing if it added

**Comment by JPLRepo** [comment]
TAC LS has always consumed O2. When a vessel runs out of O2 TAC LS will check if the vessel is in an atmosphere that contains O2 and that there is enough O2 pressure. If so; it will open the window and allow O2 in from the outside. So the kerbal's won't die.
There is no intention at this stage to change that behavior.

**Comment by JPLRepo** [comment]
Have you  read the wiki page? Have you met all the requirements on Kerbin?
https://github.com/KSP-RO/TacLifeSupport/wiki/Description

**Comment by JPLRepo** [comment]
No further information supplied for over a year. Closing.
