### ISSUE TITLE
No parts showing up for 1.4.4

### ISSUE THREAD

**Issue by dvrachakonda** [KSP-RO/TacLifeSupport#113]
None of the parts are showing up for 1.4.4. The interfaces for running out of resources is working perfectly fine. But when I start up the game, it first says that the mod wont work because I am not using 1.4.1, then it says that I placed the mod in the incorrect path. 

![image](https://user-images.githubusercontent.com/41206743/42708056-4a8ea82e-8699-11e8-8be8-da59416fcf5c.png)

![image](https://user-images.githubusercontent.com/41206743/42708024-32ca9900-8699-11e8-96ad-3c1dabe2fce4.png)

[KSP.log](https://github.com/KSP-RO/TacLifeSupport/files/2193780/KSP.log)

**Comment by JPLRepo** [comment]
Correct. TAC LS is functioning absolutely correctly.
You have not installed TAC LS into the correct folder location.
From your log:
C:\Kerbal Space Program\GameData\TacLifeSupport_0.13.9.0\GameData\REPOSoftTech\BackgroundResources\BackgroundResources.dll

TAC LS MUST be installed into the GameData folder correctly.
The correct folder location would be in your case:
C:\Kerbal Space Program\GameData\

Move the folders from C:\Kerbal Space Program\GameData\TacLifeSupport_0.13.9.0\GameData\
to:
C:\Kerbal Space Program\GameData\
