### ISSUE TITLE
Converter name should be displayed in Modules List of VAB/SPH Parts context pop-up

### ISSUE THREAD

**Issue by sumghai** [KSP-RO/TacLifeSupport#114]
Running TAC-LS v0.13.9.0 on a lightly-modded install.

I've noticed that for stock resource converters, the Modules List of the corresponding part's context pop-up dialog in the VAB/SPH Parts List shows the name of the converter:

![screenshot1](https://user-images.githubusercontent.com/4993380/45921624-5e6c6c00-befc-11e8-8ae2-19d29f167c83.png)

On the other hand, TAC-LS doesn't display the converter name, as specified by the `converterName` field of `MODULE[TacGenericConverter]`:

![screenshot0](https://user-images.githubusercontent.com/4993380/45921628-7217d280-befc-11e8-936c-0fbe8f19fa55.png)

While I understand that each TAC-LS converter serves a single purpose (as documented in its part name), I think that for the sake of consistency, the converter name should still be explicitly stated in the Module Listing. 

This would be particularly useful for third-party parts (e.g. my SDHI SMS mod) that combine two or more TAC-LS converters into the same part:

![screenshot2](https://user-images.githubusercontent.com/4993380/45921696-bce61a00-befd-11e8-8cc4-74e10e36ae65.png)

**Comment by JPLRepo** [comment]
Yup... was always there. but wrong case in the part cfg file.
Just specify the ConverterName field in the TacGenericConverter MODULE node in the part cfg.
I've fixed the TAC LS ones as well.

**Comment by sumghai** [comment]
I confirm that this issue has been fixed as of TAC LS v0.13.10.0, as well as my upcoming SDHI SMS v4.0.

Closing with thanks!
