### ISSUE TITLE
MM_CrewablePartTests.cfg version 1.6 Revamped mk2LanderCabin

### ISSUE THREAD

**Issue by SlipstreamZA** [KSP-RO/TacLifeSupport#119]
Part of the 1.6 part revamps, the mk2LanderCabin was duplicated and named as mk2LanderCabin_v2

Found a reference to it in MM_CrewablePartTests.cfg that probably needs updating?

Not sure what else would be impacted with the part name change?

**Comment by JPLRepo** [comment]
This was fixed some time ago. Closing.
