### ISSUE TITLE
Reduce log spam

### ISSUE THREAD

**Issue by siimav** [KSP-RO/TacLifeSupport#120]
Currently this mod writes too much debug information into logs. The worst part is probably ```-INFO- Tac.TacLifeSupport[FFE424F8][1002.29]: OnSave: SCENARIO``` which contains the serialized information about all the vessels and crewmembers in the current save. Maybe all this debug info shouldn't get logged by default but could be turned on if necessary through a checkbox in the game settings.

**Comment by JPLRepo** [comment]
in next version.
