### ISSUE TITLE
Background Resources throws constant NREs

### ISSUE THREAD

**Issue by RocketSquid** [KSP-RO/TacLifeSupport#123]
Version: Windows 1.7.1
Other mods: Numerous
In attempting to load a particular save, I found that TAC-LS, or more specifically Background Resource Processing, would lock the game in a constant stream of NREs until I entered the editor or exited to the main menu. Log and save are linked [here](https://drive.google.com/file/d/18dBovY1pxHTGA3Ys7I1gZMKQZeS-4lUh/view?usp=sharing) and [here](https://drive.google.com/file/d/1TX30Zr5CX-TbZV_DJ_arOcJ5Ht3LPEn-/view?usp=sharing) respectively.

**Comment by JPLRepo** [comment]
You're running KSP 1.7.1 and lots of mods... so I can't load your save without installing them all.
Besides which TAC LS hasn't been updating for KSP 1.7.x yet. so could be the reason.
Hard to say.
I've added more debug messages and error handling. But I'd suggest trying once TAC LS is updated for the KSP version you are running and try again.

**Comment by RocketSquid** [comment]
Fully updated, it still throws the errors. As far as I can tell, this only happens in the one save. Other saves function properly.

**Comment by JPLRepo** [comment]
From the log, looks to be something really wrong with a solar panel part you had installed.
Looking at the log, there are lots of mods installed, lots..... it could be any part in those mods that uses the stock solarpanel part module.
Sorry this was a while ago. Does it still occur?
I've added some extra checks to my code to prevent it spamming. But that's about all I can do.

**Comment by JPLRepo** [comment]
Closing as no response.
