### ISSUE TITLE
Error and NRE generated on entering "Settings scene".

### ISSUE THREAD

**Issue by Galenmacil** [KSP-RO/TacLifeSupport#127]
[ERR 22:37:12.389] Exception handling event OnGameSettingsApplied in class TacStartOnce:System.NullReferenceException: Object reference not set to an instance of an object
  at Tac.TacStartOnce.ApplySettings () [0x00000] in <filename unknown>:0 
  at EventVoid.Fire () [0x00000] in <filename unknown>:0 

[EXC 22:37:12.393] NullReferenceException: Object reference not set to an instance of an object
	Tac.TacStartOnce.ApplySettings ()
	EventVoid.Fire ()
	UnityEngine.Debug:LogException(Exception)
	EventVoid:Fire()
	KSP.UI.Screens.Settings.SettingsScreen:OnApply()
	KSP.UI.Screens.Settings.SettingsScreen:OnAccept()
	UnityEngine.EventSystems.EventSystem:Update()

[KSP.log](https://github.com/KSP-RO/TacLifeSupport/files/3384768/KSP.log)

**Comment by JPLRepo** [comment]
I think I found and fixed this, but can't be sure as I can't reproduce the error.

**Comment by JPLRepo** [comment]
No response, closing.
