### ISSUE TITLE
The problem with DLC Breaking Ground Expansion

### ISSUE THREAD

**Issue by blackcatIan** [KSP-RO/TacLifeSupport#129]
Hi,when I use the DLC "Breaking Ground Expansion",my kerbalman is using new  DLC science tool which need to eva on surface and press "F" key stand near by science item to handle it.It need a very long time to eva collect science point(maybe a few month?).I could not use accelerate time to get science point by DLC eva sicence station tool since tac.

So I hope there is new feature : eva kerbalman spacesuit will not lose life resouce if he is near the vessel which has life support resource, he will cost the resource nearby before the spacesuit.

**Comment by JPLRepo** [comment]
Nope. EVA kerbals have finite resources.
They have to board a vessel to replenish their life support resources.
