### ISSUE TITLE
Incompatibility with Kopernicus Bleeding Edge

### ISSUE THREAD

**Issue by TelluriumCrystal** [KSP-RO/TacLifeSupport#138]
**Versions:**
KSP v1.10.1
[Kopernicus Bleeding Edge Release 46](https://github.com/R-T-B/Kopernicus/releases/tag/UBE-release-46)
[TAC Life Support v0.16.0](https://github.com/KSP-RO/TacLifeSupport/releases/tag/V0.16.0.0)

**Issue description:**
TAC life support fails to take solar panels into account when simulating power drain on unloaded vessels with Kopernicus Bleeding Edge installed (may also be an issue with regular Kopernicus). I am unsure if this is a BackgroundResources issue or an issue with the core mod. If you take a look in the Kopernicus config folder there is a config that changes the module name of all solar panels to "KopernicusSolarPanels". My guess is this is what is causing the bug.

Related issue report in Kopericus Bleeding Edge: https://github.com/R-T-B/Kopernicus/issues/40

**Steps to reproduce:**
1. Launch game version 1.10.1 with two above mods installed
2. Start new Sandbox game
3. Launch stock rocket "Kerbal X" into orbit and maneuver into attitude where one solar panel is exposed to sunlight
4. Return to space center
5. Open Life Support Monitoring page
6. Warp forward time
7. Observe electricity remaining value decreasing despite solar panels present on Kerbal X
8. Using tracking station load back into Kerbal X in orbit
9. Observe solar panel begins to charge vessel batteries (may need to warp forward until in sunlight)

**Comment by Starstrider42** [comment]
I can confirm this on mainstream Kopernicus (version 1.9.1-13). I believe this is caused by Kopernicus/Kopernicus@58dbb96e81d7a86820fc88755d3eeae10529a235, and therefore applies to any version of Kopernicus for KSP 1.9.1 or later.

**Comment by Starstrider42** [comment]
Spoke too soon -- it looks like Kopernicus/Kopernicus@b95bbd28aa5851739d5457b29118452139d53fa4 fixes this (and all other `KopernicusSolarPanels`-related issues), though I haven't had a chance to confirm for myself yet.

**Comment by TelluriumCrystal** [comment]
Just tested it on Kopernicus Bleeding Edge release 50 and it appears to be fixed.
