### ISSUE TITLE
Older pull request not pullen in

### ISSUE THREAD

**Issue by Ristellise** [KSP-RO/TacLifeSupport#18]
Ven's New models (up to you guys if you want to pull it) :
https://github.com/taraniselsu/TacLifeSupport/pull/80
KAC compatibility :
https://github.com/taraniselsu/TacLifeSupport/pull/75

**Comment by danfarnsy** [comment]
Thanks for bringing these to my attention. I prefer the clean aspect of the current textures. The ideal aesthetic for this mod would be realism (which isn't achieved by Ven's texture here either, IMO), while the current textures are too futuristic.
