### ISSUE TITLE
Logspam is back

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/TacLifeSupport#27]
Looks like the fix that removed the log lines in TACLS's resource request method got reverted again, because I"m back to getting logspam in 0.12.2. This makes KSP write to log every frame when RO is installed, drastically slowing things down.
Look for STAGE_PRIORITY_FLOW in the codebase. Please just comment that line (and the other debug lines there).

**Comment by danfarnsy** [comment]
I'll try to get to it today.

**Comment by NathanKell** [comment]
Thanks much! :)

**Comment by JPLRepo** [comment]
@danfarnsy have you made this change?

**Comment by danfarnsy** [comment]
@JPLRepo , negative, this still needs to be made.

**Comment by JPLRepo** [comment]
Develop branch DLL available for testing.
https://github.com/KSP-RO/TacLifeSupport/tree/develop/GameData/ThunderAerospace/TacLifeSupport

**Comment by JPLRepo** [comment]
Tested successfully. Ready to Implement.
