### ISSUE TITLE
Give rescue Kerbals resources

### ISSUE THREAD

**Issue by JPLRepo** [KSP-RO/TacLifeSupport#30]
Maybe this isn't the right thread for this- but using RO, Kerbals that are spawned in rescue missions have zero life support resources in their pod- and that means that when you EVA them, they don't have any resources to take with them. Which gives you a three minute time limit to get the rescued Kerbal into your rescue ship, or they die of oxygen starvation. I just lost a Kerbal to this because I tried to use the EVA pack to burn off a little relative velocity- and that Kerbal died less than a meter from the hatch of the rescue ship! One second more and they would have survived.

I understand that they do not require resources until loaded for the first time, but at least giving them some oxygen would be nice.

**Comment by JPLRepo** [comment]
TACLS should give rescue kerbals resources.

**Comment by JPLRepo** [comment]
TAC LS does give them resources. I think something else is going on here with RO installed that means the rescue parts are not getting any LS resources. Need to investigate further.

**Comment by JPLRepo** [comment]
Needs more information as to what kind of parts. TAC LS does add these resources. So Unless something else is removing them?

**Comment by ShotgunNinja** [comment]
Some information that may help, but I admit I didn't look at TAC code at all.
- Spawned resque pods don't have a ModuleCommand, for some reasons, even when the part in question normally has it.
- Any part with crew capacity more than zero can be spawned by the game as a resque pod.
- Adding resources to a part using MM will not add it to the resque pod version of that part.
- Resque pods need to be tracked in some way to distinguish them from non-resque ones, then resources have to be setup (amount and capacity) at first contact.

Hope this is useful, cheers.

**Comment by JPLRepo** [comment]
@ShotgunNinja  Yep. Added TAC LS resources to Rescue Kerbals on EVA vessel/part first.

**Comment by JPLRepo** [comment]
Implemented in v0.12.4
