### ISSUE TITLE
easy(?) - make it not show the 'icon' in the F2 hide UI mode

### ISSUE THREAD

**Issue by DBowmanUDA** [KSP-RO/TacLifeSupport#43]
It's cosmetic but it would be much better if hide UI also hid the icon button thingy.

**Comment by JPLRepo** [comment]
What Icon are you referring to?
What version are you referring to?

**Comment by DBowmanUDA** [comment]
sorry:

example http://imgur.com/0TK5wcI.png

ThunderAerospace/TacLifeSupport/TacLifeSupport.version
{
  "NAME": "TAC Life Support",
  "URL": "http://ksp-avc.cybutek.net/version.php?id=9",
  "DOWNLOAD": "https://github.com/KSP-RO/TacLifeSupport/releases",
  "VERSION": "0.12.2",
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 1,
    "PATCH": 3
  }
}

ThunderAerospace/TacLifeSupport_v.txt
You have installed the TAC Life Support, version  ('0f56878'+'0f56878' with modifications).

**Comment by JPLRepo** [comment]
OK, what you are seeing there is the OLD version icon.
The code used to have its own Icon handling so the options were: Use Blizzy's Toolbar mod or if you didn't have that installed it created it's own icon on screen. Which is what is in your picture.
From version 0.12.3 that has been removed and TAC LS either supports Blizzy's Toolbar mod OR the stock Application Launcher icons.
If you upgrade to the latest version 0.12.4 you will get this functionality and that icon is a thing of the past. Blizzy Toolbar or the stock Application Launcher respect the F2 Hide UI option.
Please upgrade TACLS and let me know if that solves your problem.
