### ISSUE TITLE
Building on Linux (it works)

### ISSUE THREAD

**Issue by keyspace** [KSP-RO/TacLifeSupport#45]
FYI, I've been looking at this for a while, putting it off because it seemed too much.

Well, with the work I'm doing for #12, I've had to implement it some way in my [reduce-part-count branch](https://github.com/keyspace/TacLifeSupport/commits/reduce-part-count-via-firespitter), and it now builds with ~~0~~ 3 harmless warnings on Linux using MonoDevelop.

I'm not sure if the targets in `.csproj` are based on some boilerplate for KSP mods, or are hand-coded. Might look into this later. If someone knows already, please do tell.

**Comment by JPLRepo** [comment]
What is the issue here?
The targets are as I defined them. The project build files are not my design but are functional and no they are not a boilerplate for other mods.

**Comment by keyspace** [comment]
OK, cool.

This was more of a "notification" than an issue.

**Comment by keyspace** [comment]
Got the answer to my question, thanks.
