### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by antonio-gil-espinosa** [KSP-RO/TacLifeSupport#56]
When I start a new game, I receive an infinite Null Reference Exception on the debug console. Also, the mod does not work. I cannot access the status windows, and the kerbals do not die.
I tried this on a new installation, with TAC being the only installed mod.
[output_log.txt](https://github.com/KSP-RO/TacLifeSupport/files/570565/output_log.txt)

I think its because RSTKSPGameEvents.dll its not in CKAN.

**Comment by JPLRepo** [comment]
Quite possibly. As it works fine for me and I don't see it installed in your log.
CKAN metadata issues need to be taken up with the CKAN mod. This is not a TAC LS issue.
