### ISSUE TITLE
TacGenericConverter conversionRate field

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/TacLifeSupport#57]
One of the nice things of the old TACLS resource converter was that you could scale the imput/output rates by using the "conversionRate" field. Easier than changing all the rates by hand.

Since the current TACLS resource converter already adds custom parameters to the ModuleResourceConverter  (like the "requiresAtmo" parameter) would be possible to also support the "conversionRate" parameter?

**Comment by JPLRepo** [comment]
Yeah been thinking about that.
TACGenericConverter now just uses the stock ModuleResourceConverter which does not support a conversionRate. BUT, it could if I add it in.
OR, option 2 is use MM variables to do it.

**Comment by JPLRepo** [comment]
Added conversionRate field (float value accepted so can have decimal values) to TACGenericConverter. Optional PartModule field. Defaults to value of 1. Value must be > 0 otherwise is set to 1.
If supplied and not equal to 1 will multiply all inputs, outputs, requirements node resources by this value.

**Comment by PhineasFreak** [comment]
Wow, that was quick! I really appreciate it that you took the time to add it!

**Comment by JPLRepo** [comment]
No probs. should have done to begin with when I converted it over. Knew it! I haven't tested it yet. I'll do a dev build tomorrow and post here so you can test it out.

**Comment by PhineasFreak** [comment]
OK. And again, thank you!

**Comment by JPLRepo** [comment]
Here is the Dev build link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.12.7dev

**Comment by PhineasFreak** [comment]
Tested the latest release, everything is in order!

**Comment by JPLRepo** [comment]
Thanks mate. Good to hear. got a bit of noise of other bugs being reported. so will need to look at those before I do the next version release.

**Comment by PhineasFreak** [comment]
If you want go ahead and close this one.

**Comment by JPLRepo** [comment]
Yeah I will once it's released. I have to create a milestones to link it to first. Call me pedantic. I like audit trails. Plus I gotta create the change log using a script. All good. It's marked as ready to implement.
