### ISSUE TITLE
Source: HintPath is still relative in TacLifeSupport.csproj

### ISSUE THREAD

**Issue by danfarnsy** [KSP-RO/TacLifeSupport#6]
I need somebody to show me how to set the environment variables and other metadata. Until then, anybody dealing with the KSP11_update branch will have relative paths to deal with (just update your references to get it to compile).

**Comment by james3838** [comment]
I'm working on fixing it to match closer to how RO does it.  I'll see about doing pull request tonight.  Want to fix buttons first.

**Comment by james3838** [comment]
Here is my working changes cleaning up vars and using new app launcher.  There are still couple bugs, but gotta run for beer.  :)

https://github.com/james3838/TacLifeSupport/commit/64172bbb30340c0233ecd3a6b0f406b4e9b7f521

There is merge conflict with master here, so I will try to sync afterwards.

**Comment by james3838** [comment]
I tried to merge your changes with my branch, but it looks like master is broken right now.  Tons of error in logs. I rolled back my repo for now.  Let me know if you want to work together to get something stable.

[LOG 19:11:14.241] [TLS-INFO][Tac.LifeSupportModule][FFFF3D62][16.68][16.68]: OnAwake
[WRN 19:11:14.243] Could not create PartResource of type 'Food
[WRN 19:11:14.244] Could not create PartResource of type 'Water
[WRN 19:11:14.245] Could not create PartResource of type 'Oxygen
[WRN 19:11:14.246] Could not create PartResource of type 'CarbonDioxide
[WRN 19:11:14.247] Could not create PartResource of type 'Waste
[WRN 19:11:14.248] Could not create PartResource of type 'WasteWater
....

[WRN 19:11:21.474] Could not create PartResource of type 'Food
[LOG 19:11:21.481] PartLoader: Compiling Part 'ThunderAerospace/TacLifeSupportContainers/LifeSupport/TacLifeSupportContainer'
[ERR 19:11:21.483] PartCompiler: Cannot replace texture as texture replacement string is invalid. Syntax is 'origTextureName newTextureURL'
....

[LOG 19:11:22.042] PartLoader: Compiling Part 'ThunderAerospace/TacLifeSupportRecyclers/AirFilter/TacAirFilter'
[LOG 19:11:22.055] [TLS-INFO][Tac.TacGenericConverter][FFFE9602][23.18][23.18]: OnAwake
[LOG 19:11:22.058] [TLS-INFO][Tac.TacGenericConverter][FFFE9602][23.18][23.18]: Input resources parsed: 
from 
[LOG 19:11:22.060] [TLS-INFO][Tac.TacGenericConverter][FFFE9602][23.18][23.18]: Output resources parsed: 
from 
[LOG 19:11:22.062] [TLS-INFO][Tac.TacGenericConverter][FFFE9602][23.18][23.18]: OnLoad: MODULE
{
    name = TacGenericConverter
    converterName = Air Filter
    conversionRate = 20
    inputResources = IntakeAir, 0.1, ElectricCharge, 1
    outputResources = Oxygen, 0.063829787234043, false
    requiresOxygenAtmo = true
}

[LOG 19:11:22.065] [TLS-INFO][Tac.TacGenericConverter][FFFE9602][23.18][23.18]: Input resources parsed: IntakeAir, 0.1, ElectricCharge, 1, 
from IntakeAir, 0.1, ElectricCharge, 1
[LOG 19:11:22.067] [TLS-INFO][Tac.TacGenericConverter][FFFE9602][23.18][23.18]: Cannot parse "Oxygen, 0.063829787234043, false", something went wrong.
[LOG 19:11:22.068] [TLS-INFO][Tac.TacGenericConverter][FFFE9602][23.18][23.18]: Output resources parsed: 
from Oxygen, 0.063829787234043, false
[LOG 19:11:22.076] [TLS-INFO][Tac.TacGenericConverter][FFFE95FA][23.18][23.18]: OnAwake
[LOG 19:11:22.077] [TLS-INFO][Tac.TacGenericConverter][FFFE95FA][23.18][23.18]: Input resources parsed: IntakeAir, 0.1, ElectricCharge, 1, 
from IntakeAir, 0.1, ElectricCharge, 1
[LOG 19:11:22.079] [TLS-INFO][Tac.TacGenericConverter][FFFE95FA][23.18][23.18]: Cannot parse "Oxygen, 0.063829787234043, false", something went wrong.
[LOG 19:11:22.081] [TLS-INFO][Tac.TacGenericConverter][FFFE95FA][23.18][23.18]: Output resources parsed: 
from Oxygen, 0.063829787234043, false
[LOG 19:11:22.086] PartLoader: Compiling Part 'ThunderAerospace/TacLifeSupportRecyclers/Recycler_CarbonExtractor/TacCarbonExtractor'
[ERR 19:11:22.094] [ShipTemplate]: No Resource definition found for RESOURCE

..........

[LOG 19:11:39.939] [TLS-INFO][Tac.TacLifeSupport][FFFCECFA][32.56][32.56]: Constructor
[EXC 19:11:39.945] NullReferenceException: Object reference not set to an instance of an object
    Tac.GlobalSettings.set_Food (System.String value)
    Tac.GlobalSettings..ctor ()
    Tac.TacLifeSupport..ctor ()
    UnityEngine.GameObject:AddComponent(Type)
    ScenarioRunner:AddModule(String)
    ScenarioRunner:AddModule(ConfigNode)
    ProtoScenarioModule:Load(ScenarioRunner)
    <OnLevelWasLoaded>c__Iterator8E:MoveNext()

**Comment by danfarnsy** [comment]
@james3838 , I like where you're going with this. It's definitely cleaner, minus the errors and exceptions you have at the moment. :) Tomorrow, I'd like to see about integrating the changes in your commit/PR on my end, see if I can avoid whatever conflict you might be running into. Let's make a new "spring cleaning" branch from current master and go from there. Also, I still haven't figured out how to set the ($KSP) environment variable, which means I'm likely to run into trouble with relative references again in trying to tell it where the working KSP folder is. Grr. How do I set that?

**Comment by james3838** [comment]
Two ways to set KSP
1) Go to your environment variables and create one called KSP and set vale to path.
2) Edit the KSPPath.inc file in root and replace default I set.
First is preferable (there's a powershell cmd that can do it too).  Second is set to program files path steam typically installs to.  So if you use steam it might just work as I now.

For development, I suggest we work out of dev branches and only merge to master when there is a flea build, and are able to load mod in ksp with no errors.

**Comment by danfarnsy** [comment]
Tomorrow I'll take a look at fixing that. Right now I'm a bit
incapacitated. I agree re: development branches. Merge with master when
it's release time. By the way, what's your KSP forum username? I keep
referring to you as james3838, but I haven't tagged you properly there.
I've made sure to emphasize the credit you deserve for the work on this.
I'm absolutely grateful you're here to provide some expertise on the
programming side, to make up for my inexperience. The only thing I'm
bringing to the table is some free time to learn and drive to get some
momentum behind coordinating people's work so it gets in users hands. I'd
be stuck in the water still trying to update this myself if it wasn't for
your contributions.

**Comment by james3838** [comment]
If you want to give me access to repo, I can create a staging branch and bring my changes over.  Just cleaned up last couple issues I was seeing.

**Comment by danfarnsy** [comment]
You should have already received an invite to the KSP-RO team, just checked with @NathanKell . Check your github notices?

**Comment by james3838** [comment]
Yup, have access now.

**Comment by james3838** [comment]
I merged #14 into Stable-1.1.2.  Feel free to build/give this branch a try.  @danfarnsy, I reverted several of your recent changes from this branch.  I would propose if it works, we publish this for now as we work on the other enhancements for future release.  I did see one bug in the logs (mentioned above). I will investigate and see if I can fix it.

**Comment by JPLRepo** [comment]
Working on fixing all this up for 1.1.3 Master Branch deployment.
Have it all working in Develop branch - except have to decipher original TaranisElsu BAT files for TEST and RELEASE deployment and re-factor these as I think they are also using KSP environment Variable but in different context.

Current Requirements for others to have environment set-up correctly are:
First Create a Windows Environment Variable called "KSP" - Don't include the "s. 
The value of this Variable should be the absolute file path to your KSP KSP-Data\Managed or where you have located the
KSP and Unity DLL's for the current version of KSP (The Assembly-CSharp.dll, UnityEngine.dll, etc, etc).
Here is a guide to create the Windows Environment Variable.
http://www.computerhope.com/issues/ch000549.htm

Install MSBuild Extensions
https://github.com/mikefourie/MSBuildExtensionPack/releases
Download the Zip and install it.

**Comment by JPLRepo** [comment]
I believe I have resolved and setup most of this. I couldn't get the MSBuild extensions auto-increment of assembly numbers to work. So setting it manually in the AssemblyInfo.
I haven't done a deploy build so once that is done and all working in the next deploy I will write detailed instructions.
