### ISSUE TITLE
Broken TACLS Sabatier Recycler, 2.5m

### ISSUE THREAD

**Issue by scaiper** [KSP-RO/TacLifeSupport#62]
Closing "}" is missing in Recycler_SabatierCarbonRecyclerLarge.cfg after CarbonDioxide input. Causing module to not produce anything.

**Comment by JPLRepo** [comment]
<sob> <sob> If only I had more volunteer testers to check this stuff before I release it.

**Comment by JPLRepo** [comment]
Implemented in 0.12.8
