### ISSUE TITLE
Counter is started immediately for landed rescuable kerbals

### ISSUE THREAD

**Issue by petersohn** [KSP-RO/TacLifeSupport#63]
Rescuing kerbals works normally when I have to rescue them from orbit and they sit in their craft. However, if they start landed and sit outside their craft, then the resource counter gets started immediately and it runs out before I would have time to rescue them.

**Comment by JPLRepo** [comment]
oh dear... forgot about those.
I'll have to fix.

**Comment by JPLRepo** [comment]
Implemented in 0.12.8
