### ISSUE TITLE
Not showing up in CKAN

### ISSUE THREAD

**Issue by smeely** [KSP-RO/TacLifeSupport#65]
Not sure if it is intentional or not, but I have been trying to get TACLS through CKAN and no matter what I search for and what filter I set it to it won't bring it up. The Stock config addon does come up but when you click on it the following message comes up:

> Module TACLS has not been found. This may be because it is not compatible with the currently installed version of KSP.

![ckan error](https://cloud.githubusercontent.com/assets/24596403/21244992/467798ca-c374-11e6-8b10-1db78babe2a1.jpg)

However when I filter "Incompatible" it doesn't come up either.

KSP 1.2.2

Just curious as to whether this is an issue or intentional.

Thanks in advance

**Comment by SaitamOcir** [comment]
+1

**Comment by cherrydev** [comment]
I think I've tracked down the reason for this. CKAN didn't index the new release because the version number didn't change as far as CKAN was concerned. The November 8th release was named TacLifeSupport_V0.12.7.zip and the newer release was also named TacLifeSupport_V0.12.7.zip.

**Comment by smeely** [comment]
Thanks. I'm looking forward to having it automatically update and manage all my mods for me again :).

**Comment by JPLRepo** [comment]
Closing this is not a TAC LS issue.
Issue is with CKAN.

**Comment by cherrydev** [comment]
Well, CKAN can't 'fix' this because it has no way to see the two releases apart, since they're named the same in the GitHub repo. If someone could bump the version number, it'll be fixed.

**Comment by cherrydev** [comment]
@JPLRepo do you mind if edit the latest release so that the new release build reads 0.12.8?

**Comment by JPLRepo** [comment]
Sounds like a CKAN limitation to me.
There are no two 0.12.7 versions of TAC LS.
The previous version was a DEV build called V0.12.7dev
and then there was a release version called V0.12.7

So the version is V0.12.7
I am not able to make a change to TAC LS at this time to change it to V0.12.8 without doing a release.
The AVC version checking system would need to be updated as well as the AVC .version file in the released zip file.
Here we go again, a limitation in CKAN. I personally don't use it, and don't support it for these reasons.
I don't have time to fix this limitation in the CKAN mod as I am on holidays.

**Comment by smeely** [comment]
I don't know how CKAN works, I would have assumed it used some sort of version file which specified latest version of ksp it was compatible with... I wish I could manually tell CKAN to install anyway, but that is not your problem. Just wondered if there was some sort of workaround you were going to work on.

**Comment by smeely** [comment]
Actually, A further note. I tried to do a force install with ckan command line, but that's when I noticed its not even showing up as an incompatible mod. TACLS isn't there. the TACLS stock config one is there, but it requires TACLS which doesn't exist according to the index.
