### ISSUE TITLE
Resources in the vessel are being calculated incorrectly when a pilot go EVA

### ISSUE THREAD

**Issue by ilushcenko-nc** [KSP-RO/TacLifeSupport#69]
Please find a step by step information in the screenshots. If you actually need logs for this issue, please let me know and I provide them. 

So, in brief, if I set a consumption rate higher that default (I tried x10 higher), then this rate seems to affect the amount of resource that is being taken from the vessel's storage into the EVA suit. But when the kerbal getting back to the vessel, the amount of returned resource is correct. This means that if I just repeat unboard-board operation several times, then life support resources will vanish, making any complex long-term missions impossible.

In the images you can see many other mods installed, but this issue is reproducible in the clean environment as well.

Please let me know if you need any additional information from me.

Settings
![ksp1](https://cloud.githubusercontent.com/assets/23450723/21560860/a2364eda-ce7e-11e6-8696-46bbeca34f9e.png)

Before unboarding
![ksp2](https://cloud.githubusercontent.com/assets/23450723/21560858/a235eb0c-ce7e-11e6-9a36-078ce9199016.png)

After unboarding - EVA
![ksp3](https://cloud.githubusercontent.com/assets/23450723/21560862/a23787dc-ce7e-11e6-88c4-96e7c4540289.png)

After unboarding - vessel
![ksp4](https://cloud.githubusercontent.com/assets/23450723/21560859/a2363be8-ce7e-11e6-865f-108217180097.png)

After boarding back
![ksp5](https://cloud.githubusercontent.com/assets/23450723/21560861/a2368882-ce7e-11e6-9721-3c31a060ce50.png)

**Comment by JPLRepo** [comment]
Confirmed... I think. Did you perhaps Change the resource amounts after starting the new game?
I think TAC LS is not changing the max amounts an EVA kerbal can carry if you change the resource amounts on a current game. If you increase them, it becomes a problem. If you decrease them it's not a problem.

**Comment by ilushcenko-nc** [comment]
Yes, you are right. First time a have faced this problem, I changed rates after starting a game. When I made screenshots, I begun new sandbox game, and set up rates before the start (as far as I remember...), so I'm not sure if this is a root cause. 

By the way, I'd like to clarify, just in case. TAC LS does not change the max amount of resources that EVA can carry, it change the amount of resource to be taken from the vessel when a kerbonaut leave the vessel. For instance, as per images above, there was 7.6 of Food in the beginning. When Jeb leaves the vessel, you can see that EVA contains 0.37 of Food and vessel contains 3.95 of food. If I multiply this value accordingly to the difficulty setting: (0.37 * 10) + 3.95 = 7.65, I get the initial amount (approximately).

Anyway, thank you for the response, I really appreciate your work.

**Comment by JPLRepo** [comment]
Here is how it works. TAC LS will calculate the maximum amount of each resource an EVA kerbal can carry. 
Currently it is only doing this at the start of a new game when you Start KSP.
It calculates this based on the amount of food you set in the settings to be consumed, water, air, EC.
If you change it after you start a game, or if you change it after you have already loaded a game and then start a new one (without restarting KSP) it won't re-calculate the amounts and change them.
So what is happening is when you EVA it takes a larger amount of each resource. but there is not enough room for them to carry it all. so it is dumped.
I've already made the code changes to fix this. But have to test it, then will be in the next version. In the meantime, best thing to do is change the amounts in the settings for your game. then Restart KSP. Each time you restart KSP it will re-calculate the maximum amounts correctly and setup the EVA kerbal resources correctly.

**Comment by JPLRepo** [comment]
Implemented in 0.12.8
