### ISSUE TITLE
Location of items duplicated

### ISSUE THREAD

**Issue by ghost** [KSP-RO/TacLifeSupport#73]
why is there a need for the items to be duplicated in utilities and life support, why can they not be just in life support?

**Comment by JPLRepo** [comment]
Hmm. Thought I had fixed that but it appears it isn't.
Well kind of. They are appearing twice if you have Community Category Kit installed and use the CCK category.
If you remove the CCK folder from GameData and just use the built-in TAC LS category they only appear in the TAC LS category and not the Utilities category.
I'll have to have another look at it.

**Comment by ghost** [comment]
the problem is, other parts use CCK, which would end up being reinstalled again on update since I use CKAN.

**Comment by JPLRepo** [comment]
If you cannot uninstall it then you will have to wait until I fix it. sorry.
When that will be I cannot say.

**Comment by ghost** [comment]
not a problem.. I am in no rush.. It is a good mod, and I know we all do this for fun..

**Comment by Jozay3125** [comment]
I was able to fix this myself by going into all the TLS folders for Containers, Hex Cans, and Recyclers (I left MTF alone since I don't use real fuels or modular fuel tanks) and changed the category from "Utility" to "none." I haven't noticed any negative side effects... yet, but I will let you know as I play on.

**Comment by SynthWeaver** [comment]
If someone need those edited files I have them here for version 1.2.2:
https://www.dropbox.com/sh/ji5ztpy1elz8fhb/AAC1FI6r7cZxgZtmGcqUPTpya?dl=0
:D :D :D

**Comment by JPLRepo** [comment]
I don't see this happening on the latest version... or the newly coming version for 1.4.1.
So I consider it resolved.
