### ISSUE TITLE
Recyclers are not working

### ISSUE THREAD

**Issue by Key-Pe** [KSP-RO/TacLifeSupport#76]
Whenever I use any of the recyclers on one of my ships they just don´t work. They only sometimes work when I manually turn them off and back on again so this might be because they don´t do anything while I am not currently in the ship.

**Comment by JPLRepo** [comment]
They don't work when not active vessel. but they should catchup when you do switch to them.
They work the same as stock resourceconverters.
So not sure what your problem is. and without logs and/or a save file there's not a lot I can do.

**Comment by JPLRepo** [comment]
No response. Closing.
