### ISSUE TITLE
Adnormal water consumption

### ISSUE THREAD

**Issue by KX99Ex** [KSP-RO/TacLifeSupport#78]
Hello, recently i've dealing with a rather interesting bug...
The water supply in my vessel is building up instead of dropping...
The vessel has 6 crew members on board, with 1 water purifier. According to the mod setting, there will be a water loss at 0.351619L per day; water purifier's ability has been taken into consideration.
However... as the following screenshots...
At day 205, i have 2408L of water on board, with 48.36L of waste water.
![screenshot1064](https://cloud.githubusercontent.com/assets/26347158/23824452/1bcb0d92-06b2-11e7-8285-8670ee24cd02.png)
20 days later, i still have 2408L of water, but with 53.08L of waste water... Since the water purifier is running, does that mean the purifier is generating more water than the waste water input? Or there is something else generating water? [not sure Kerbals generate water or not... I do have a carben extractor on board and running].
![screenshot1066](https://cloud.githubusercontent.com/assets/26347158/23824454/1bd3fdda-06b2-11e7-99a6-241ac47c0217.png)
This is the corresponding log file. 
[output_log.zip](https://github.com/KSP-RO/TacLifeSupport/files/835886/output_log.zip)

**Comment by KX99Ex** [comment]
Just checked your configuration file.
For every 1.1188078704E-05 liter of fresh water consumed, Kerbal will produce 1.4247685185E-05 liter of waste water. There is a multiplication of 1.2735.
At the same time, water purifier will generate 1.2822916667E-05 L of fresh water for the same amount of waste water. This leads to a water generation rate of 0.9. So the overall water consumption will be -0.1462....  And the water level will build up rather than drop down. Thus it means if there is enough water purifier on board, the water will never running out. This cant be right...

**Comment by JPLRepo** [comment]
yes that doesn's sound right does it.
Adjusted purifiers to produce 0.000011188078704 Water base rate.

**Comment by KX99Ex** [comment]
If water generation lower to that level, to balance the mass there will be 0.000004269919367L/s solid waste generated. The ship would still recover all the water and doesn't lose any. Might be a little boring, but anyway. Thanks for your reply.
