### ISSUE TITLE
Time warp issue

### ISSUE THREAD

**Issue by KX99Ex** [KSP-RO/TacLifeSupport#79]
Hello
There is another problem i've encountered. 
For a vessel that has enough power supply, if i turn the time warp to maximum level[100000x], I will receive this message almost immediately. And the warp will be suspended.
![screenshot1066](https://cloud.githubusercontent.com/assets/26347158/23824521/33a39744-06b3-11e7-89c2-4da2410df84b.png)
For warping while inside the tracking station, the same thing happens but warp will not stop. Also at the end of the warp, no Kerbals will be dead. It seems at max warp, electricity generation is not calculated or something.

If I use 10000x time or lower, this issue does not appear.

This is a log file
[output_log.zip](https://github.com/KSP-RO/TacLifeSupport/files/835891/output_log.zip)

**Comment by JPLRepo** [comment]
I've made an adjustment that I think resolves this but no time to test it.

**Comment by KX99Ex** [comment]
Oh great, could you give us a beta version? i will be more than happy to try it out

**Comment by KX99Ex** [comment]
[output_log.zip](https://github.com/KSP-RO/TacLifeSupport/files/870077/output_log.zip)
![screenshot1077](https://cloud.githubusercontent.com/assets/26347158/24322894/9a8d9a8c-11a7-11e7-9328-76c6ec834e35.png)
The problem remains with todays version...And it's even worse, this time it actually killed my crew
