### ISSUE TITLE
Bug: TACLS v0.12 throws NullReferenceException

### ISSUE THREAD

**Issue by cgokmen** [KSP-RO/TacLifeSupport#8]
Hello,

I updated to TACLS v0.12 today. I am running KSP 1.1.2 and was using v0.11.3 just fine without any problems. Since I updated TACLS, I am no longer able to enter the VAB or the SPH, and cannot exit to the main menu or to the KSC screen when I'm in any other building.

After a short inspection of the debug logs I see this error:

```
[EXC 22:09:06.919] NullReferenceException: Object reference not set to an instance of an object
    Tac.TacLifeSupport.OnSave (.ConfigNode gameNode)
    ScenarioModule.Save (.ConfigNode node)
    ProtoScenarioModule..ctor (.ScenarioModule module)
    ScenarioRunner.GetUpdatedProtoModules ()
    Game.Updated ()
    GamePersistence.SaveGame (System.String saveFileName, System.String saveFolder, SaveMode saveMode)
    VehicleAssemblyBuilding.OnClicked ()
    SpaceCenterBuilding.EnterBuilding ()
    SpaceCenterBuilding.OnLeftClick ()
    KSP.UI.Screens.SpaceCenter.BuildingPickerItem.OnPointerClick (UnityEngine.EventSystems.PointerEventData data)
    UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
    UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
    UnityEngine.EventSystems.EventSystem:Update()
```

If you need anything else for a fix, I can provide it here. Thank you!

**Comment by danfarnsy** [comment]
@sultanskyman Did you install manually or via CKAN? And while I'm not sure it's relevant, can you provide a list of your mods? Also, can you provide your complete log file (since I was unable to replicate the issue)?

**Comment by cgokmen** [comment]
Installed thru CKAN, here's a CKAN mod dump, you can just change the txt extension to ckan and load it.

[moddump.txt](https://github.com/KSP-RO/TacLifeSupport/files/262132/moddump.txt)

**Comment by danfarnsy** [comment]
I'll get back to you later. See if uninstalling via CKAN and then installing manually resolves the issue. If it does, that means it's a CKAN install issue I've got to fix. Thanks for the info. I'll be AFK until this evening.

**Comment by cgokmen** [comment]
Alright, will try through CKAN on a clean install and also manually on this one. I'll keep you posted when I have results.

**Comment by cgokmen** [comment]
Wow, that was fast - after I got it to work after installing manually, I figured something was wrong with the CKAN meta - and the issue was that while the plugin depends on the Community Resource Pack it does not have it as a dependency on CKAN, so the pack wasn't installed automatically.

I fixed my issue by installing the resource pack manually, but the fix on your side is adding
`{"name" : "CommunityResourcePack" },`
to the CKAN meta's dependency section.

Thank you very much for your help!

**Comment by danfarnsy** [comment]
Thank you for your help, too! I caught a few minutes, so I'm submitting a PR to update the netkan file.

**Comment by gregslomin** [comment]
I'm still running into this same exactly issue and stack trace with .12.2. Originally installed from CKAN but then uninstalled and reinstalled manually. 

This is a fresh installation of KSP and the only mods that were installed were all of the suggested/recommended mods from RO.

**Comment by JPLRepo** [comment]
I'm not sure what a NullReference Error has to do with CKAN?
Can you please support your whole Output log thanks so I can see what is going on.

The error appears to be while tranisition Unity game scene and TAC LS is attempting to save your TAC LS data.

**Comment by gregslomin** [comment]
I don't think it necessarily has anything to do with CKAN. As I said it happened with both a manual and CKAN install. I mentioned it because it seemed like pertinent information.

Removing TACLS makes everything work fine though. I'll post my entire log tonight.
