### ISSUE TITLE
Multiplying kerbals

### ISSUE THREAD

**Issue by Zaccy200** [KSP-RO/TacLifeSupport#80]
I'm having a problem with kerbals appearing in the crafts that aren't loaded and consuming the life support. The kerbals pop in every time I go on EVA or load in a new craft and they can keep spawning regardless of crew capacity.
First time going EVA
![screenshot426](https://cloud.githubusercontent.com/assets/26517805/24079173/f685af22-0cbc-11e7-85f2-a2b43863544f.png)

Second time on EVA
![screenshot427](https://cloud.githubusercontent.com/assets/26517805/24079174/0269ca30-0cbd-11e7-9e5f-511fd8ff8e25.png)

Third time on EVA
![screenshot428](https://cloud.githubusercontent.com/assets/26517805/24079177/139be5ae-0cbd-11e7-8067-dfae2cfe09d8.png)

I'm not quite sure on what is causing the issue but I thought I may as well post it here. I can only seem to fix the kerbals by switching to the craft with them in it or quicksaving.

**Comment by JPLRepo** [comment]
No log... or save file... can't help.

**Comment by gfmvs** [comment]
same problem here. Every time when i do a crew transfer, other unloaded ship will get more kerbals.
Go back to space center return to normal, but still happen next time.

**Comment by JPLRepo** [comment]
This is very old. Wondering if this still occurs on latest version.
