### ISSUE TITLE
Time warp issue remains

### ISSUE THREAD

**Issue by KX99Ex** [KSP-RO/TacLifeSupport#82]
![screenshot1077](https://cloud.githubusercontent.com/assets/26347158/24322918/e46806d8-11a7-11e7-81c7-ccb7f1a51b29.png)
![screenshot1089](https://cloud.githubusercontent.com/assets/26347158/24322917/e4634c56-11a7-11e7-8617-af79a7386338.png)
[output_log.zip](https://github.com/KSP-RO/TacLifeSupport/files/870078/output_log.zip)

Hi, just tested your new version. The time warp issue remains and getting worse. This time it actually killed 2 of the crew members. The time warp is so fast i cant capture the moment the electricity ran out, but it is after that moment 2 crew died. All other supplies seems to be functional but the electricity was not.
I will try it with stock game, it might be a bug with KSP

**Comment by KX99Ex** [comment]
The stock game seems okay... At max time warp the electricity does not depletes.

**Comment by KX99Ex** [comment]
Status Update
The electricity value is pretty stable at 10000x speed. For this ship the remained time dropped to something like 2min43s = 163s. At 1000x speed, it's 30min16s, 1816s. At 1x speed, it's 85d = 1836000s. As the warp ratio gets higher, the remaining estimation dropped non-linearly. So I guess at 100000x, if the battery is not big enough [and it's enough for any other ratio], the calculation result drops again so it run out. Currently it can be worked around by doing time warp at KSC or put a huge battery [something like 150k times bigger than the consume rate].

**Comment by JPLRepo** [comment]
Try the dev build.
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.3dev

**Comment by JPLRepo** [comment]
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Comment by JPLRepo** [comment]
Please try dev build from this link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev
