### ISSUE TITLE
LifeSupport.cfg is not distributed with the mod by default on CKAN which can cause issues with RO

### ISSUE THREAD

**Issue by shimmythejj** [KSP-RO/TacLifeSupport#83]
\GameData\ThunderAerospace\TacLifeSupport\LifeSupport.cfg 

Currently in CKAN, the cfg file is installed under "TAC Life Support (TACLS) - Stock Config", not the mod itself and isn't required. Other mods such as Realism Overhaul that attempt to modify the file using a Module Manager config will not work unless this file exists first. Currently there doesn't appear to be any alternate configs for TACLS in CKAN to choose from either. Possibly the "TAC Life Support (TACLS)" and "TAC Life Support (TACLS) - Stock Config" could be either combined or at least the mod depending on the config.

**Comment by shimmythejj** [comment]
Submitted a related issue to KSP-RO/RealismOverhaul
https://github.com/KSP-RO/RealismOverhaul/issues/1621

**Comment by danfarnsy** [comment]
Just need a fix on the CKAN side. I'll look into it.

**Comment by Olympic1** [comment]
Fixed in https://github.com/KSP-CKAN/NetKAN/pull/5450

**Comment by danfarnsy** [comment]
Thanks.
