### ISSUE TITLE
Rescue missions impossible!?

### ISSUE THREAD

**Issue by malnvenshorn** [KSP-RO/TacLifeSupport#84]
Hi there,

today I just started my first rescue mission with this addon and noticed that when I finally reached the pod in the orbit of Kerbin the Kerbal was already out of oxygen for about an hour. It seems that resources are consumed since I accepted that mission. Since they don't have any resources on board this makes it impossible to rescue Kerbals which are further away.

**Comment by stratochief66** [comment]
What sort of mode were you playing? Did you have RO installed, or RP-0?

**Comment by malnvenshorn** [comment]
I'm playing in career mode. RO and RP-0 are not installed.

**Comment by JPLRepo** [comment]
What version of KSP and TACLS?
Don't suppose you have the logs? or save files/automatic backup saves?

**Comment by malnvenshorn** [comment]
KSP v 1.2.2, TACLS v 0.13.0

Does this addon provide logs? Where can I find them? And no I don't have any save game of this situation.

What should be the behavior of TACLS? Are rescue pods excluded or how does it work?

**Comment by franciscoexmachina** [comment]
Hi,

Thank you in advance for whatever help you can provide.

I too get multiple consecutive crashes when trying to board a vessel during a "rescue" mission. I've noticed the resources count is negative for the "rescued" subject before s/he boards the player vessel. I have not been able to upload a save game via a zip file (github does not like my zips or rars), but please let me know if the save file is required, so I will try and find out a way to upload a compressed file.
As you can tell by the screenshot I have several MODS installed. Let me know if you need a list.

[output_log.txt](https://github.com/KSP-RO/TacLifeSupport/files/1054878/output_log.txt)
[output_log.txt](https://github.com/KSP-RO/TacLifeSupport/files/1054884/output_log.txt)
[output_log.txt](https://github.com/KSP-RO/TacLifeSupport/files/1054886/output_log.txt)





![screenshot 2017-06-06 21 36 34](https://cloud.githubusercontent.com/assets/29228864/26827797/216056d8-4b02-11e7-9712-78440d22d0f5.png)

**Comment by JPLRepo** [comment]
Please try dev build from this link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev
