### ISSUE TITLE
Electricity BUG

### ISSUE THREAD

**Issue by hzx10** [KSP-RO/TacLifeSupport#87]
KSP Version 1.3、TAC Life Support v0.13.2、（default setting） Electricity Consumption have BUG、  MOD storage is no problem、  my English level low, Unclear expression   sorry
BUG appear： in increase time warp situation         .There's only one Mod

**Comment by JPLRepo** [comment]
Try the dev build.
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.3dev

**Comment by JPLRepo** [comment]
Try this build
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Comment by JPLRepo** [comment]
Please try dev build from this link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev
