### ISSUE TITLE
Bugs found during work on the translation

### ISSUE THREAD

**Issue by Tirathangil** [KSP-RO/TacLifeSupport#88]
#A bug was found during the translation into Russian. Line #autoLOC_TACLS_00144 is a description of the container, but instead is used in the container name. Accordingly, line #autoLOC_TACLS_00145 is its description, but at the same time it is the name of another container. In this case, the #autoLOC_TACLS_00143  line is not used anywhere.

ADD: Line #autoLOC_TACLS_00187 no effect - in name of canister displayed "autoLOC_TACLS_00187".

**Comment by Tirathangil** [comment]
I'm fixed this bugs. The first bug was in file "FoodSmall.cfg" in "TacLifeSupportContainers" - the numbers were mixed. The second bug was in file "LargeWaste.cfg" in "TacLifeSupportHexCanWaste" dir - there was no # before "autoLOC_TACLS_00187".

ADDED: I found a similar bug in the settings window ("Editor Filter" option). Error in Sources/SettingsParams.cs, line 60. The attribute "ToolTip" is equal to the first parameter in this function.

**Comment by JPLRepo** [comment]
Thank you. Fixed for next version.

**Comment by Tirathangil** [comment]
~~@JPLRepo  I have a some questions about translation item.
"If enabled TAC LS will process resources on unloaded vessels.\nIf disabled, it won't and play the catchup and estimation game." - Did it mean that inactive ships (when this option disabled) are not processed in any way? By the way, how is it determined that the vessel is "unloaded"?~~
 
UPD: I'm always will googleing info, before asking the question...

And second question: "The Minutes between List Sorting for the Vessel List" - Do I understand correctly that after N minutes of real time, the ship, whose resources are less, will be top of the list?

Thank you very much for answers.

**Comment by JPLRepo** [comment]
Yes unloaded ships are not processed in any way if you turn off that option.

Second question: This is how long in minutes the ships in the list will be sorted. Yes, you are correct.
