### ISSUE TITLE
Bug w/ Alerts (Electricity)

### ISSUE THREAD

**Issue by Kataklysmos** [KSP-RO/TacLifeSupport#90]
I, and a couple other people it seems like, have noticed a bug with the alerts involving electricity. The timers count down only what the ships capacity is, without taking into account the fact that the ship may have regained power with solar panels, rtg's, etc. This is obviously pretty frustrating, to constantly have a red alert on the alert tab. 

![screenshot 6](https://user-images.githubusercontent.com/29267483/26909657-1a30a5ba-4bd0-11e7-9df2-b6a914d8a652.png)

This screenshot shows a full electric charge meter with an overdue alert for the ship having no electricity.

Log File:  (Hopefully the right one, I haven't done this much before)

[output_log.txt](https://github.com/KSP-RO/TacLifeSupport/files/1059776/output_log.txt)

**Comment by JPLRepo** [comment]
Yes, so does this occur without BackgroundProcessing mod installed?

**Comment by Kataklysmos** [comment]
whoops.... I didn't see the section explaining that. I just installed it, and I'll assume it'll work with that.

**Comment by JPLRepo** [comment]
Can you advise me if installing BackgroundProcessing mod fixed the problem?
I am working on doing the same as that mod inside TAC LS.

**Comment by Kataklysmos** [comment]
It doesn't seem to have fixed the problem.

![screenshot 12](https://user-images.githubusercontent.com/29267483/26960732-6e6283ec-4ca7-11e7-8884-f25137102a15.png)

![screenshot 13](https://user-images.githubusercontent.com/29267483/26960855-67f9a8e0-4ca8-11e7-9bcf-7fd4c262b01a.png)

I was a bit confused because the "REPO SoftTech" folder that was in the TAC LS GameData folder had a file called "Background Resources," so it seemed that I had two things, one called "Background Resources," and one called "Background Processing." As far as I can tell, I have everything installed right, though, so the background processing isn't working and the alert is showing up as having no electric charge even when the vessel clearly does.

[output_log.txt](https://github.com/KSP-RO/TacLifeSupport/files/1062995/output_log.txt)

**Comment by pozar87** [comment]
Hello!
I can also confirm this bug. Likely I have a save just before most of my orbital station crew went to past :) What is odd only 2 out of 3 active ships (with the crew on board) are affected...
Do you need some logs and/or mod list?

**Comment by JPLRepo** [comment]
Try the dev build.
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.3dev

**Comment by misterB0420** [comment]
I'm unsure if that fixed it for the above posters, but it is unfortunately still happening to me, using the dev build and your most recent copy of background processing

**Comment by JPLRepo** [comment]
Well, that's because in the instructions for the dev build it says to uninstall BackgroundProcessing mod.
Try that.

**Comment by pozar87** [comment]
Hi JPLRepo,
I removed the `REPOSoftTech` folder and replace `ThunderAerospace/TacLifeSupport` from **v0.13.3dev** (perhaps I should override it all? I wasn't sure since the `BackgroundResources` was also there)
The problem is partially gone - seems like my Kerbals are safe again :) - Thanks! 
However the computed remaining times seems a bit odd:

![tac_ls](https://user-images.githubusercontent.com/9629954/27255109-7142da5c-5397-11e7-8a2e-63ca3f39a81c.png)

The values are negative and quite close to 32 bit max int in milliseconds (close, but not exact...) 

Thanks for all your effort!

**Comment by misterB0420** [comment]
heh oops, didn't see that bit, sorry. yep, works like a charm. thanks for the awesome mod!

**Comment by wardog21** [comment]
having the same problem and there is a stupid workaround:
in the save file there is for each vessel the lastupdate number
VesselInfo
			{
				vesselName = Kerbin Space Station
				vesselType = Station
				vesselSituation = ORBITING
				vesselIsPreLaunch = False
				numCrew = 5
				numFrozenCrew = 0
				numOccupiedParts = 3
				lastUpdate = 1015119.0987060822
				lastFood = 1015119.0987060822
				lastWater = 1015119.0987060822
				lastOxygen = 1015119.0987060822
				lastElectricity = 1014220.8871309602

all number increase but the lastElectricity. you can copy it from any other and replace the lastElectricity value. i think it could be easy fixed?`cause it still sucks to do it all the time for each vessel..

**Comment by Kataklysmos** [comment]
I'm a little late to the party now, but the dev build did fix the issue. Thanks!

**Comment by MuhsinFatih** [comment]
dev build didn't fix my issue. BackgroundProcessing is not installed

**Comment by JPLRepo** [comment]
Shall look into it.

**Comment by JPLRepo** [comment]
Try this build https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Comment by JPLRepo** [comment]
Please try dev build from this link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Comment by snapped** [comment]
I ran into the same issue (vanilla KSP 1.3 x64 only HyperEdit and TACLS installed). Once I installed v0.13.4dev (updating REPOSoftTech and ThunderAerospace folders) it worked again. Thanks for the fix!
