### ISSUE TITLE
v0.13.3dev solar panels not recharging on background ships

### ISSUE THREAD

**Issue by gmobrien** [KSP-RO/TacLifeSupport#92]
**KSP version:** 1.3.0 Windows 64bit

**Mods installed:**

- TacLifeSupport v0.13.3.dev
- Kerbal Engineer Redux 1.1.3.0

**Reproduction steps:**

1. Build a ship with batteries and solar panels that includes life support modules.
2. Focus on another ship or return to KSC.
3. The batteries on your craft will be depleted regardless of whether or not the solar panels are working properly.

At any time by taking control of the ship in question you can recharge the batteries, but if you do not do so the vessel will run out of electricity and the crew will die.

[output_log.txt](https://github.com/KSP-RO/TacLifeSupport/files/1117209/output_log.txt)

**Comment by gmobrien** [comment]
Reinstalling BackgroundProcessing appears to resolve the issue.

https://github.com/JPLRepo/background-processing/releases/tag/v0.4.5.0

**Comment by MuhsinFatih** [comment]
What do you mean reinstalling? BackgroundProcessing is not included in the mod in the first place. BackgroundResources is

**Comment by JPLRepo** [comment]
Hmm... sounds like a bug in BackgroundResources. Shall look into it.

**Comment by gmobrien** [comment]
Reinstalling, as in I installed it after having removed it based on the instructions here: http://forum.kerbalspaceprogram.com/index.php?/topic/146465-13-tac-life-support-v0132-release-29th-may-2017/&do=findComment&comment=3088627

In any case after further testing, I seem to have been incorrect in suggesting that this resolves the issue.  I'm not sure what led me to this conclusion, but I was in a rush so assume it was user error.

**Comment by JPLRepo** [comment]
Try this build:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Comment by JPLRepo** [comment]
Please try dev build from this link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Comment by MuhsinFatih** [comment]
I would love to try and give feedback but unfortunately I won't be able to play at least a month. Sorry
