### ISSUE TITLE
Electricity Running Out Too Soon Bug?  

### ISSUE THREAD

**Issue by jimbob123x** [KSP-RO/TacLifeSupport#94]
##  ** Kerbals Dying Of Lack Of Power While Battery Still Half Full!**

I am not sure if this has been brought up previously but I have noticed what i believe is a bug, no matter what kind of situation my Kerbals are in, be it on the launch pad with nothing but the batteries in the capsule or a station with a huge amount of power, the electricity remaining in the TAC Life Support Monitoring Screen (LMS) is said to be less then that available.

When it runs out, of course my Kerbals die, however there is still useable electricity sometimes in the same command module as them. The number that is shown in the LMS although it does increase if more batteries are added, does not seem to correlate with how much power is left.     

If you need anything is regards to this bug please let me know. 
Many thanks, a concerned Kerbalnaut.

**Comment by jimbob123x** [comment]
Nevermind, I have realised that they aren't dying, but the Alerts are going off at the wrong times due to not factoring in the solar panels. I realise that this has already been raised, feel free to close my issue without a comment as I know that you are already trying to fix this. My apologies.

**Comment by JPLRepo** [comment]
Try this build:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Comment by JPLRepo** [comment]
Please try dev build from this link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev
