### ISSUE TITLE
3.14 not using any suppliers

### ISSUE THREAD

**Issue by Jimbodiah** [KSP-RO/TacLifeSupport#95]
TAC is not consuming any resources in my game. I've checked stock pods to be sure it was not mod related, but it's the same thing. All my LS counters show negative numbers in white. Tried warping at max (in orbit) but no resources are used.

Logs:
http://jimbodiah.com/ksp/tac.zip

**Comment by tycharp** [comment]
I've also had this issue

**Comment by JPLRepo** [comment]
Please try dev build from this link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Comment by tycharp** [comment]
I will try next time I'm on. Thank you for your response

**Comment by Jimbodiah** [comment]
Unless you changed the software and not updated the version number, that is the version I was running.

**Comment by JPLRepo** [comment]
Correct. I updated it just before the last post. Same version as dev build

**Comment by Jimbodiah** [comment]
OK< I will test it and let you know.

**Comment by tycharp** [comment]
I'm afraid it's not working still
Logs:
https://drive.google.com/open?id=0B5KI-QrBsXeMdWN3X1dGZmNnZTQ

Picture of my game data folder:
https://drive.google.com/open?id=0B5KI-QrBsXeMWVprbVY1UWJsTkU

**Comment by tycharp** [comment]
Could it be a problem with how I configured the save?

**Comment by tycharp** [comment]
I found something that could be leading to the issue.
The time in the upper left hand corner seems to be infinite in the beginning unless I toggle the time mode from MET to UT.
https://docs.google.com/document/d/10iB8BAL_fCJWi8TnzS3PdpLhZqPb-MrLKk-Lqu2Lnyk

**Comment by JPLRepo** [comment]
Are you saying that before you toggle the time display the resources are not being consumed or working correctly? and then after you toggle it they begin working correctly?
That is just a display. I can't see how it's related.

**Comment by tycharp** [comment]
Didnt realize this... my Kerbals didn't start consuming resources once I toggled the time mode. Maybe just ignore that :D

**Comment by JPLRepo** [comment]
I'm going to assume this is fixed, as no one has indicated otherwise.

**Comment by JPLRepo** [comment]
@tycharp  This is the error in your LOG:
[RESOURCES] - Error in - ResourceMap_GetAbundance - System.NullReferenceException: Object reference not set to an instance of an object
  at ResourceUtilities. () [0x00000] in <filename unknown>:0 
  at ResourceMap.GetAbundance (AbundanceRequest request) [0x00000] in <filename unknown>:0 

It is a stock error message.
It is caused by the stock code being unable to find Resource Maps for the planets.
I'm guessing one of your mods has badly broken the RESOURCES cfg files in your install.

**Comment by Jimbodiah** [comment]
np, stopped using any mod that has resources like LS as they never work properly and only screw up games.
