### ISSUE TITLE
Kerbals instantly dying when losing resources

### ISSUE THREAD

**Issue by BlackMoons** [KSP-RO/TacLifeSupport#96]
Seems like kerbals are instantly dying when they lose oxygen/EC/Food/Water now in my save.
Even newly launched ships. 

Steps to reproduce: launch ship and drain its resources, like using TAC Fuel balancer to dump all water. 
Kerbal instantly dies when the 'Water depleted' message is given. 

[Savegame.zip](https://github.com/KSP-RO/TacLifeSupport/files/1180840/Savegame.zip)

**Comment by rgeber** [comment]
Same here. Double checked the "Without" Settings in game and in the JSON file. All set to default. But lose a resource for a second and they all die. Also applies at very high time warp 10K - 100K. Using 0.13.4.

[Deadly_TAC_LS_savegame.zip](https://github.com/KSP-RO/TacLifeSupport/files/1181075/Deadly_TAC_LS_savegame.zip)

**Comment by JPLRepo** [comment]
Please try new dev build from this link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Comment by BlackMoons** [comment]
Kerbals no longer seem to be instantly dying when they run outta resources. Yay.

**Comment by JPLRepo** [comment]
Fixed for next release
