### ISSUE TITLE
Changed TAC-LS Limits back to default after game restart

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/TacLifeSupport#97]
In Game Difficulty settings I changed the max. time values for Electricity and Oxygen, after restarting KSP the values were resetted to default.

**Comment by JPLRepo** [comment]
More information required. Can you confirm you changed these values for an already started game and then restarted KSP and reloaded the same save game and went back to the difficulty settings and they were reset?
The settings are reset/default for any new game. But should persist when you change them with a save game loaded (at the KSC).

**Comment by Gordon-Dry** [comment]
Yes, I can confirm that.
The settings were reset in the save game after restarting KSP.

**Comment by JPLRepo** [comment]
Fixed for next release.
