### ISSUE TITLE
Immediate generalized death

### ISSUE THREAD

**Issue by KBluey** [KSP-RO/TacLifeSupport#99]
I updated to the most recent version of TAC-LS, and when I reloaded KSP and my persistent save, all my Kerbals immediately died from air toxicity!  I had two vessels in orbit, and all the Kerbals aboard both died, except for Val who was in a Hitchhiker module.

I tried reinstalling the mod, reloading etc. etc., still the same problem.  The vessels they were in had been functioning reliably for a long time, so I'm 100% certain it wasn't player error.

[output_log.txt](https://github.com/KSP-RO/TacLifeSupport/files/1220323/output_log.txt)

**Comment by JPLRepo** [comment]
Did you follow the instructions on the forum?
1) Backed up your saves?
2) Checked the difficulty settings for resource consumption after updating TAC LS and opening and closing the save?

**Comment by KBluey** [comment]
The instructions are in the Wiki, not the Forum.  But yes, I did those things.

**Comment by KBluey** [comment]
Oh, and I checked the vessels immediately afterward; they both had food, oxygen, water and EC.

**Comment by JPLRepo** [comment]
Can you update your save file as follows:
 Look for these values:
lastElectricity = 
and change the value to be the same as the others for each vessel and tell me what happens when you reload.

**Comment by KBluey** [comment]
I made those changes and reloaded the save file, and all my Kerbals are alive!!  Thanks.

**Comment by JPLRepo** [comment]
That's good news. Was this a save from a previous version of TAC LS?
Trying to determine if I still have a problem. Or it's a hangover from the bugs... that I thought I had now fixed.

**Comment by KBluey** [comment]
Yes, the save was from the previous version.

-----Original Message-----

**Comment by KBluey** [comment]
Come to think of it, I did constantly see messages about EC running out in the previous version, when I knew it wasn't.

-----Original Message-----

**Comment by JPLRepo** [comment]
I consider this resolved unless it has occurred in the latest version.
